services:
  bot_wp_arca:
    build: .
    tty: true
    stdin_open: true
    restart: unless-stopped
    container_name: bot_wp_arca
    ports:
      - "${APPPORT}:3000/tcp"
    volumes:
      - ./data:/app/data
    environment:
      WEBSERVICEDIR: "${WEBSERVICEDIR}"
      TESTMODE: "${TESTMODE}"
      COOLDOWNTIME: "${COOLDOWNTIME}"
      MAXATTEMPTS: "${MAXATTEMPTS}"
      APP_USE_OPENAI_API: "${APP_USE_OPENAI_API}"
      REASONINGEFFORT: "${REASONINGEFFORT}"
      AUDIO: "${AUDIO}"
      URL: "${URL}"
      MODEL: "${MODEL}"
      APIKEY: "${APIKEY}"
      HISTORYFILE: "${HISTORYFILE}"
      MAXTOKENS: "${MAXTOKENS}"
      APP_COMMAND_PREFIX: "${APP_COMMAND_PREFIX}"
      APP_SQLITE_DATABASE: "${APP_SQLITE_DATABASE}"
      APPPORT: "3000"
      MASTERKEY: "${MASTERKEY}"
      APPENDPOINT: "${APPENDPOINT}"
      ONLYUSERMESSAGES: "${ONLYUSERMESSAGES}"
      USEDEFAULTWEBSERVICE: "${USEDEFAULTWEBSERVICE}"
      DEFAULTWEBSERVICEDIR: "${DEFAULTWEBSERVICEDIR}"
      DEFAULTWEBSERVICECUIT: "${DEFAULTWEBSERVICECUIT}"
      BROWSERPATH: "/usr/bin/chromium"