services:
  bot_wp_arca:
    build: .
    tty: true
    stdin_open: true
    restart: unless-stopped
    container_name: bot_wp_arca
    ports:
      - "${APPPORT}:3000/tcp"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      WEBSERVICEDIR: "${WEBSERVICEDIR}"
      TESTMODE: "${TESTMODE}"
      COOLDOWNTIME: "${COOLDOWNTIME}"
      MAXATTEMPTS: "${MAXATTEMPTS}"
      USEAI: "${USEAI}"
      REASONINGEFFORT: "${REASONINGEFFORT}"
      AUDIO: "${AUDIO}"
      URL: "${URL}"
      MODEL: "${MODEL}"
      APIKEY: "${APIKEY}"
      HISTORYFILE: "${HISTORYFILE}"
      MAXTOKENS: "${MAXTOKENS}"
      COMMANDPREFIX: "${COMMANDPREFIX}"
      MAXMESSAGES: "${MAXMESSAGES}"
      APPPORT: "3000"
      MASTERKEY: "${MASTERKEY}"
      APPENDPOINT: "${APPENDPOINT}"
      CLIENTSFILE: "${CLIENTSFILE}"
      ONLYUSERMESSAGES: "${ONLYUSERMESSAGES}"
      USEDEFAULTWEBSERVICE: "${USEDEFAULTWEBSERVICE}"
      DEFAULTWEBSERVICEDIR: "${DEFAULTWEBSERVICEDIR}"
      DEFAULTWEBSERVICECUIT: "${DEFAULTWEBSERVICECUIT}"
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"